const BULK_DISCOUNT_THRESHOLD = 30;
const BULK_DISCOUNT_RATE = 0.25;

const TUESDAY = 2;
const TUESDAY_DISCOUNT_RATE = 0.1;

export { BULK_DISCOUNT_RATE, BULK_DISCOUNT_THRESHOLD, TUESDAY, TUESDAY_DISCOUNT_RATE };
